// let unti:{[keys: string]: number} = {};
// unti["unti"] = 114514;
// unti["yaju"] = 1919;
// unti["tnok"] = 893;
var ngo = { roman: "unti", value: 1919 };
var ngo2 = { roman: "ngo2", value: 810 };
console.log(ngo);
console.log(ngo2);
console.log();
ngo = ngo2;
console.log(ngo);
console.log(ngo2);
console.log();
ngo2 = { roman: "dfjsak;", value: 181293 };
console.log(ngo);
console.log(ngo2);
console.log();
ngo = { roman: "aaaaaa", value: 111 };
console.log(ngo);
console.log(ngo2);
